apiVersion: v1
kind: Service
metadata:
  namespace: log-output
  name: pingpong-svc
spec:
  type: NodePort
  selector:
    app: pingpong
  ports:
    - port: 2346
      protocol: TCP
      targetPort: 3001
