apiVersion: batch/v1
kind: CronJob
metadata:
  name: daily-todos
  namespace: project
spec:
  schedule: "5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: daily-todos
              image: sannahan/daily-todos:e2.09.02
              env:
                - name: HOST
                  value: "todo-backend-svc:2346"
          restartPolicy: OnFailure