apiVersion: v1
kind: Service
metadata:
  namespace: pingpong
  name: pingpong-svc
spec:
  type: LoadBalancer
  selector:
    app: shared
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3001
