apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: project
    spec:
      volumes:
        - name: image-volume
          persistentVolumeClaim:
            claimName: image-claim
      containers:
        - name: todo-app
          image: APP-PROJECT/IMAGE
          env:
          - name: PORT
            value: "8082"
          - name: BACKEND_URL
            value: "http://todo-backend-svc:2346/todos"
          volumeMounts:
          - name: image-volume
            mountPath: /usr/src/app/files
          #commented out because local runs so slow atm
          #resources:
          #  limits:
          #    cpu: "100m"
          #    memory: "50Mi"
        - name: todo-backend
          image: BACKEND-PROJECT/IMAGE
          env:
          - name: PORT
            value: "8085"
          - name: PGHOST
            value: postgres-svc
          - name: PGDATABASE
            value: project
          - name: PGUSER
            value: admin
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-password
                key: POSTGRES_PASSWORD
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 5
            httpGet:
              path: /healthz
              port: 8085
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 5
            httpGet:
              path: /healthz
              port: 8085
          #commented out because local runs so slow atm
          #resources:
          #  limits:
          #    cpu: "100m"
          #    memory: "50Mi"