apiVersion: v1
kind: Service
metadata:
  namespace: log-output
  name: log-output-svc
spec:
  type: ClusterIP
  selector:
    app: shared
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 3000