name: Build and publish application

on:
  push:
    branches:
      - main
    paths:
      - 'part4/e4.07/**'
      - '.github/workflows/gitops.yml'

jobs:
  build-publish:
    name: Build, Push, Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # tag image with the GitHub SHA to get a unique tag
      - name: Build and publish log-output
        run: |-
          cd ./part4/e4.07/log-output && docker build --tag "sannahan/log-output:$GITHUB_SHA" .
          docker push "sannahan/log-output:$GITHUB_SHA"

      - name: Build and publish pingpong
        run: |-
          cd ./part4/e4.07/pingpong && docker build --tag "sannahan/pingpong:$GITHUB_SHA" .
          docker push "sannahan/pingpong:$GITHUB_SHA"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Use right image for log-output
        run: cd ./part4/e4.07 && kustomize edit set image LOG-OUTPUT/IMAGE=sannahan/log-output:$GITHUB_SHA

      - name: Use right image for pingpong
        run: cd ./part4/e4.07 && kustomize edit set image PINGPONG/IMAGE=sannahan/pingpong:$GITHUB_SHA

      - name: commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: 'kustomization.yaml'
          message: New version released ${{ github.sha }}